# Generated by Django 5.2 on 2025-05-05 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="activities",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("dates", models.DateField()),
                ("days", models.CharField(max_length=255)),
                ("starttime", models.TimeField()),
                ("endtime", models.TimeField()),
                ("Discription", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="admin",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="companies",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("companyName", models.CharField(max_length=255)),
                ("Email", models.CharField(max_length=255)),
                ("mobile", models.IntegerField()),
                ("manage", models.CharField(max_length=255)),
                ("statuss", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="invoice",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("accountNumber", models.CharField(max_length=255)),
                ("account", models.CharField(max_length=255)),
                ("Amount", models.IntegerField()),
                ("invoiceDate", models.CharField(max_length=255)),
                ("dueDate", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="leads",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=255)),
                ("Title", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("phone", models.IntegerField()),
                ("email", models.CharField(max_length=255)),
                ("lead_status", models.CharField(max_length=255)),
                ("Lead_created", models.CharField(max_length=255)),
                ("Lead_owner", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="prequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("contactno", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("services", models.CharField(max_length=255)),
                ("others", models.CharField(max_length=255)),
                ("query", models.CharField(max_length=255)),
                ("status", models.SmallIntegerField()),
                ("posting_date", models.DateField()),
                ("remark", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="tasks",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("Taskname", models.CharField(max_length=255)),
                ("deadLine", models.DateField(max_length=255)),
                ("status", models.CharField(max_length=255)),
                ("Asignee", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ticket",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("User_Name", models.CharField(max_length=255)),
                ("email_id", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("task_type", models.CharField(max_length=255)),
                ("prioprity", models.CharField(max_length=255)),
                ("ticket", models.CharField(max_length=255)),
                ("attachment", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
                ("admin_remark", models.CharField(max_length=255)),
                ("posting_date", models.DateField()),
                (
                    "admin_remark_date",
                    models.DateTimeField(default=datetime.datetime.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="user",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("alt_email", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("mobile", models.CharField(max_length=255)),
                ("gender", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("status", models.IntegerField()),
                ("posting_date", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="usercheck",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("logindate", models.CharField(max_length=255)),
                ("logintime", models.CharField(max_length=255)),
                ("user_id", models.IntegerField()),
                ("username", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("ip", models.CharField(max_length=255)),
                ("mac", models.BinaryField()),
                ("city", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="usernotification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=255)),
                ("status", models.IntegerField()),
                ("statusdata", models.CharField(max_length=255)),
                ("remark", models.CharField(max_length=255)),
            ],
        ),
    ]
